name: Test

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
  cleanup-runs:
    runs-on: ubuntu-18.04
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
  check-label:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run pack
      - uses: ./
        with:
          required_all: 'approved'
          required_oneof: 'patch,minor,major'
