name: Test

on:
  pull_request

jobs:
  check-label:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          required_all: 'approved'
          required_oneof: 'patch,minor,major'
